version: "3.8"

services:
  backend:
    image: victor823543/focus-api:latest
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: "mongodb+srv://victor:${MONGO_PASSWORD}@focuscluster0.tr9g7.mongodb.net/testing_db?retryWrites=true&w=majority&appName=FocusCluster0"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN}"
      ACTIVE_DB: "test"

  frontend:
    image: victor823543/focus-frontend:latest
    ports:
      - "80:80"
